name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean and Refresh Gradle
      run: ./gradlew clean --refresh-dependencies

    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Upload APK/AAB as Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Build-Artifacts
        path: app/build/outputs/**

    - name: Upload Logs for Debugging
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Gradle-Logs
        path: build/reports/**
