name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Grant execute permissions for Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Clean and refresh dependencies
    - name: Clean and Refresh Gradle
      run: ./gradlew clean --refresh-dependencies

    # Step 5: Build the project
    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info

    # Step 6: Run tests
    - name: Run Unit Tests
      run: ./gradlew test

    # Step 7: Upload build outputs as artifacts
    - name: Upload APK/AAB as Artifacts
      if: success()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build-Artifacts
        path: app/build/outputs/**

    # Step 8: Cache debug logs for further troubleshooting
    - name: Upload Logs for Debugging
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Gradle-Logs
        path: build/reports/**
